//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHOffice.Core.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillStateHistory = new HashSet<BillStateHistory>();
        }
    
        public long bid { get; set; }
        public string no { get; set; }
        public string sender { get; set; }
        public string sender_tel { get; set; }
        public string receiver { get; set; }
        public string receiver_tel { get; set; }
        public string receiver_addr { get; set; }
        public string post { get; set; }
        public Nullable<long> agent_uid { get; set; }
        public string goods { get; set; }
        public decimal insurance { get; set; }
        public string i_express { get; set; }
        public string i_no { get; set; }
        public bool confirmed { get; set; }
        public Nullable<long> confirmer { get; set; }
        public bool enabled { get; set; }
        public string remarks { get; set; }
        public BHOffice.Core.Business.Bill.BillStates state { get; set; }
        public System.DateTime last_state_updated { get; set; }
        public System.DateTime bill_date { get; set; }
        public System.DateTime created { get; set; }
        public long creater { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<long> updater { get; set; }
    
        public virtual User Agenters { get; set; }
        public virtual User Creaters { get; set; }
        public virtual ICollection<BillStateHistory> BillStateHistory { get; set; }
    }
}
