//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHOffice.Core.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillStateHistory
    {
        public long bhid { get; set; }
        public long bid { get; set; }
        public long creater { get; set; }
        public System.DateTime state_updated { get; set; }
        public System.DateTime created { get; set; }
        public BHOffice.Core.Business.Bill.BillStates state { get; set; }
        public bool enabled { get; set; }
        public string remarks { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
