//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHOffice.Core.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bill = new HashSet<Bill>();
            this.Bill1 = new HashSet<Bill>();
        }
    
        public long uid { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string name { get; set; }
        public System.DateTime created { get; set; }
        public bool enabled { get; set; }
        public BHOffice.Core.Business.UserRoles role { get; set; }
    
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual ICollection<Bill> Bill1 { get; set; }
    }
}
